### ISSUE TITLE
Fail to import jinja2

### ISSUE THREAD

**Issue by m-mizutani** [yu-iskw/gpt-code-review-action#11]
I tried gpt-code-review-action in my OSS [repository](https://github.com/m-mizutani/alertchain), however it failed to import python module. How can I fix it? Please let me know if you need more information.

# Error message

```
Traceback (most recent call last):
  File "/app/entrypoint.py", line 19, in <module>
    from langchain import PromptTemplate
  File "/usr/local/lib/python3.10/site-packages/langchain/__init__.py", line 6, in <module>
    from langchain.agents import MRKLChain, ReActChain, SelfAskWithSearchChain
  File "/usr/local/lib/python3.10/site-packages/langchain/agents/__init__.py", line 2, in <module>
    from langchain.agents.agent import (
  File "/usr/local/lib/python3.10/site-packages/langchain/agents/agent.py", line 17, in <module>
    from langchain.chains.base import Chain
  File "/usr/local/lib/python3.10/site-packages/langchain/chains/__init__.py", line 2, in <module>
    from langchain.chains.api.base import APIChain
  File "/usr/local/lib/python3.10/site-packages/langchain/chains/api/base.py", line 8, in <module>
    from langchain.chains.api.prompt import API_RESPONSE_PROMPT, API_URL_PROMPT
  File "/usr/local/lib/python3.10/site-packages/langchain/chains/api/prompt.py", line 2, in <module>
    from langchain.prompts.prompt import PromptTemplate
  File "/usr/local/lib/python3.10/site-packages/langchain/prompts/__init__.py", line 3, in <module>
    from langchain.prompts.chat import (
  File "/usr/local/lib/python3.10/site-packages/langchain/prompts/chat.py", line 10, in <module>
    from langchain.memory.buffer import get_buffer_string
  File "/usr/local/lib/python3.10/site-packages/langchain/memory/__init__.py", line 11, in <module>
    from langchain.memory.entity import (
  File "/usr/local/lib/python3.10/site-packages/langchain/memory/entity.py", line 8, in <module>
    from langchain.chains.llm import LLMChain
  File "/usr/local/lib/python3.10/site-packages/langchain/chains/llm.py", line 11, in <module>
    from langchain.prompts.prompt import PromptTemplate
  File "/usr/local/lib/python3.10/site-packages/langchain/prompts/prompt.py", line 8, in <module>
    from jinja2 import Environment, meta
ModuleNotFoundError: No module named 'jinja2'
```

https://github.com/m-mizutani/alertchain/actions/runs/4737718901/jobs/8410826552?pr=12

# GitHub Action

https://github.com/m-mizutani/alertchain/blob/2c4a175d4ae95b8a457bfcd1e849107a04a12977/.github/workflows/review.yml

Ref: https://github.com/m-mizutani/alertchain/pull/12

**Comment by yu-iskw** [comment]
The issue might be caused by the updates of langchain. It seems that the issue was already resolved. If the issue still happens, please feel free to reopen the issue.

- https://github.com/hwchase17/langchain/issues/3113
- https://github.com/hwchase17/langchain/releases/tag/v0.0.144
